<?php

namespace Neoan3\Component\Gdpr;

use Neoan3\Frame\BluaBlue;

/**
 * Class GdprController
 * @package Neoan3\Component\Gdpr
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class GdprController extends BluaBlue {
    /**
     * Route: Gdpr
     */
    function init(): void
    {
        $this->renderer->includeElement('Gdpr');
        $this->hook('main', 'gdpr', []);
        $this->output();
    }

}
