<?php

namespace Neoan3\Component\Sdk;

use Neoan3\Frame\BluaBlue;

/**
 * Class SdkController
 * @package Neoan3\Component\Sdk
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class SdkController extends BluaBlue {
    /**
     * Route: Sdk
     */
    function init(): void
    {
        $this->renderer->includeElement('Sdk');

        $this->hook('main', 'sdk', [
            'sdks' => [
                [
                    'lang'=> 'PHP',
                    'description'=>'Easy to use Guzzle-based API wrapper',
                    'repo'=>'https://github.com/blua-blue/blua-blue-php-sdk#readme'
                ],
                [
                    'lang'=> 'JavaScript',
                    'description'=>'Universal SDK for node, deno and the browser',
                    'repo'=>'https://github.com/blua-blue/blua-blue-js#readme'
                ]
            ]
        ]);
        $this->output();
    }

}
