<?php

namespace Neoan3\Component\Verification;

use Neoan3\Frame\BluaBlue;

/**
 * Class VerificationController
 * @package Neoan3\Component\Verification
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class VerificationController extends BluaBlue {
    /**
     * Route: Verification
     */
    function init(): void
    {
        $this->renderer->includeElement('Verification');
        $this->hook('main', 'verification', []);
        $this->output();
    }

}
