<?php

namespace Neoan3\Component\Write;

use Neoan3\Frame\BluaBlue;
use Neoan3\Provider\Auth\Authorization;

/**
 * Class WriteController
 * @package Neoan3\Component\Write
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class WriteController extends BluaBlue {
    /**
     * Route: Write
     */
    #[Authorization('restrict')]
    function init(): void
    {
        $this->renderer->includeElement('Write');
        $this->hook('main', 'write', []);
        $this->output();
    }

}
