<?php

namespace Neoan3\Component\WriteVideo;

use Neoan3\Frame\BluaBlue;

/**
 * Class WriteVideoController
 * @package Neoan3\Component\WriteVideo
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class WriteVideoController extends BluaBlue {
    /**
     * Route: WriteVideo
     */
    function init(): void
    {
        $this->renderer->includeElement('WriteVideo');
        $this->hook('main', 'writeVideo', []);
        $this->output();
    }

}
