<?php

namespace Neoan3\Component\Footer;

use Neoan3\Frame\BluaBlue;

/**
 * Class FooterController
 * @package Neoan3\Component\Footer
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class FooterController extends BluaBlue {
    /**
     * Route: Footer
     */
    function init(): void
    {
        $this->renderer->includeElement('Footer');
        $this->hook('main', 'footer', []);
        $this->output();
    }

}
