<?php

namespace Neoan3\Component\Header;

use Neoan3\Frame\BluaBlue;

/**
 * Class TestController
 * @package Neoan3\Component\Header
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class HeaderController extends BluaBlue {
    /**
     * Route: Test
     */
    function init(): void
    {
        $this->renderer->includeElement('Header', []);
        $this->output();
    }

}
