<?php

namespace Neoan3\Component\ContactUs;

use Neoan3\Apps\Db;
use Neoan3\Core\RouteException;
use Neoan3\Frame\BluaBlue;
use Neoan3\Model\Message\MessageModel;
use Neoan3\Model\Message\MessageModelWrapper;
use Neoan3\Provider\Model\InitModel;

/**
 * Class ContactUsController
 * @package Neoan3\Component\ContactUs
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ContactUsController extends BluaBlue {
    /**
     * Route: ContactUs
     */
    function init(): void
    {
        $this->renderer->includeElement('ContactUs');
        $this->hook('main', 'contactUs', []);
        $this->output();
    }


    /**
     * @throws RouteException
     */
    #[InitModel(MessageModel::class)]
    function postContactUs($body)
    {
        try{
            $this->honeyPot($body['code']);
            $message = new MessageModelWrapper($body);
            $message->setIsRead(false);
            $message->setSubject('contact-us');
//            Db::debug();
            return $message->store()->toArray();
        } catch (\Exception $e){
            var_dump($e->getMessage());
            throw new RouteException('Format or Bot issue',406);
        }

    }

}
