<?php

namespace Neoan3\Component\Login;

use Neoan3\Frame\BluaBlue;
use Neoan3\Frame\Hybrid;
use Neoan3\Provider\Auth\Authorization;

/**
 * Class LoginController
 * @package Neoan3\Component\Login
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class LoginController extends BluaBlue {
    /**
     * Route: Login
     */
    function init(): void
    {
        $this->renderer->includeElement('Login');
        $this->hook('main', 'login', [])->output();
    }

}
