<?php

namespace Neoan3\Component\Privacy;

use Neoan3\Frame\BluaBlue;

/**
 * Class PrivacyController
 * @package Neoan3\Component\Privacy
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class PrivacyController extends BluaBlue {
    /**
     * Route: Privacy
     */
    function init(): void
    {
        $this->renderer->includeElement('Privacy');
        $this->hook('main', 'privacy', []);
        $this->output();
    }

}
