<?php

namespace Neoan3\Component\Search;

use Neoan3\Frame\BluaBlue;

/**
 * Class SearchController
 * @package Neoan3\Component\Search
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class SearchController extends BluaBlue {
    /**
     * Route: Search
     */
    function init(): void
    {
        $this->renderer->includeElement('Search');
        $this->hook('main', 'search', []);
        $this->output();
    }

}
