<?php

namespace Neoan3\Component\Articles;

use Neoan3\Frame\BluaBlue;
use Neoan3\Model\Article\ArticleModel;
use Neoan3\Provider\Model\InitModel;

/**
 * Class ArticlesController
 * @package Neoan3\Component\Articles
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ArticlesController extends BluaBlue {
    /**
     * Route: Articles
     */
    #[InitModel(ArticleModel::class)]
    function init(): void
    {
        $this->renderer->includeElement('Articles');
        $condition = sub(1) ? ['keywords'=>'%'.sub(1).'%','^delete_date'] : ['^delete_date'];
        $articles = ArticleModel::find($condition,['orderBy'=>['insert_date','desc'],'limit'=>[0,3]]);
        $this->hook('main', 'articles', ['articles' => $articles]);
        $this->output();
    }

}
