<?php

namespace Neoan3\Component\Api;

use Neoan3\Frame\BluaBlue;
use Neoan3\Frame\Demo;

/**
 * Class ApiController
 * @package Neoan3\Component\Api
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ApiController extends Demo {
    /**
     * Route: Api
     */
    function init(): void
    {
//        $this->hook()
        $this->renderer->includeJs('https://unpkg.com/@stoplight/elements/web-components.min.js');
        $this->renderer->includeElement('Api');
        $this->hook('main', 'api', []);
        $this->output();
    }

}
