<?php

namespace Neoan3\Component\Keywords;

use Neoan3\Frame\BluaBlue;

/**
 * Class KeywordsController
 * @package Neoan3\Component\Keywords
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class KeywordsController extends BluaBlue {
    /**
     * Route: Keywords
     */
    function init(): void
    {
        $this->renderer->includeElement('Keywords');
        $this->hook('main', 'keywords', []);
        $this->output();
    }

}
