<?php

namespace Neoan3\Component\WriteMarkdown;

use Neoan3\Frame\BluaBlue;

/**
 * Class WriteMarkdownController
 * @package Neoan3\Component\WriteMarkdown
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class WriteMarkdownController extends BluaBlue {
    /**
     * Route: WriteMarkdown
     */
    function init(): void
    {
        $this->renderer->includeElement('WriteMarkdown');
        $this->hook('main', 'writeMarkdown', []);
        $this->output();
    }

}
