<?php

namespace Neoan3\Component\Ip;

use Neoan3\Frame\BluaBlue;

/**
 * Class IpController
 * @package Neoan3\Component\Ip
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class IpController extends BluaBlue {
    /**
     * Route: Ip
     */
    function init(): void
    {
        $this->renderer->includeElement('Ip');
        $this->hook('main', 'ip', []);
        $this->output();
    }

}
