<?php

namespace Neoan3\Component\Home;

use Neoan3\Frame\BluaBlue;

/**
 * Class HomeController
 * @package Neoan3\Component\Home
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class HomeController extends BluaBlue {
    /**
     * Route: Home
     */
    function init(): void
    {
        $this->renderer->includeElement('Home');
        $this->hook('main', 'home', []);
        $this->output();
    }

}
