<?php

namespace Neoan3\Component\Webhook;

use Neoan3\Frame\BluaBlue;
use Neoan3\Model\Webhook\WebhookModel;
use Neoan3\Provider\Auth\Authorization;
use Neoan3\Provider\Model\InitModel;

/**
 * Class WebhookController
 * @package Neoan3\Component\Webhook
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class WebhookController extends BluaBlue {
    /**
     * Route: Webhook
     */
    function init(): void
    {
        $this->renderer->includeElement('Webhook');
        $this->hook('main', 'webhook', []);
        $this->output();
    }
    #[Authorization('restrict',['all'])]
    #[InitModel(WebhookModel::class)]
    public function getWebhook()
    {
        return WebhookModel::find(['^delete_date','user_id'=> '$'.$this->authObject->getUserId()]);
    }
    #[Authorization('restrict',['all'])]
    #[InitModel(WebhookModel::class)]
    public function postWebhook($body)
    {
        $body['user_id'] = $this->authObject->getUserId();
        return WebhookModel::create($body);
    }
}
