<?php

namespace Neoan3\Component\Comments;

use Neoan3\Frame\BluaBlue;

/**
 * Class CommentsController
 * @package Neoan3\Component\Comments
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class CommentsController extends BluaBlue {
    /**
     * Route: Comments
     */
    function init(): void
    {
        $this->renderer->includeElement('Comments');
        $this->hook('main', 'comments', []);
        $this->output();
    }

}
