<?php

namespace Neoan3\Component\Profile;

use Neoan3\Frame\BluaBlue;
use Neoan3\Model\Article\ArticleModel;
use Neoan3\Model\User\UserModel;
use Neoan3\Provider\Model\InitModel;

/**
 * Class ProfileController
 * @package Neoan3\Component\Profile
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ProfileController extends BluaBlue {
    /**
     * Route: Profile
     */
    #[InitModel(UserModel::class)]
    #[InitModel(ArticleModel::class)]
    function init(): void
    {
        if(!sub(1)){
            redirect(default_ctrl);
        }
        $user = $this->getProfile(sub(1));
        if(empty($user)){
            redirect(default_ctrl);
        }
        $this->renderer->includeElement('Profile');

        $this->hook('main', 'profile', ['user'=> $user, 'articles'=>$user['articles']]);
        $this->output();
    }
    #[InitModel(UserModel::class)]
    #[InitModel(ArticleModel::class)]
    function getProfile($userName): array
    {

        $authUser = null;
        try{
            $authUser = $this->Auth->validate();
            $only_public = false;
        } catch (\Exception $e){
            $only_public = true;
        }
        $user = UserModel::find(['user_name'=>$userName]);
        if(empty($user)){
            return [];
        }
        $user = $user[0];
        $condition = ['author_user_id' => '$' . $user['id'],'^delete_date'];
        if($only_public){
            $condition['is_public'] = 1;
            $condition['publish_date'] = '!';
            unset($user['user_email']);
            unset($user['user_profile']);
        }
        $user['articles'] = ArticleModel::find($condition,['orderBy'=>['insert_date','desc']]);
        return $user;
    }

}
