<?php

namespace Neoan3\Component\WriteInterface;

use Neoan3\Frame\BluaBlue;

/**
 * Class WriteInterfaceController
 * @package Neoan3\Component\WriteInterface
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class WriteInterfaceController extends BluaBlue {
    /**
     * Route: WriteInterface
     */
    function init(): void
    {
        $this->renderer->includeElement('WriteInterface');
        $this->hook('main', 'writeInterface', []);
        $this->output();
    }

}
