<?php

namespace Neoan3\Component\Share;

use Neoan3\Frame\BluaBlue;

/**
 * Class ShareController
 * @package Neoan3\Component\Share
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class ShareController extends BluaBlue {
    /**
     * Route: Share
     */
    function init(): void
    {
        $this->renderer->includeElement('Share');
        $this->hook('main', 'share', []);
        $this->output();
    }

}
