<?php

namespace Neoan3\Component\WriteHtml;

use Neoan3\Frame\BluaBlue;

/**
 * Class WriteHtmlController
 * @package Neoan3\Component\WriteHtml
 *
 * Generated by neoan3-cli for neoan3 v3.*
 */

class WriteHtmlController extends BluaBlue {
    /**
     * Route: WriteHtml
     */
    function init(): void
    {
        $this->renderer->includeElement('WriteHtml');
        $this->hook('main', 'writeHtml', []);
        $this->output();
    }

}
